export { initApi, getApiConfig, getStorageUrl, authFetch, publicFetch, ApiError, isOfflineError, buildQuery, jsonBody } from './client'
export type { ApiConfig } from './client'

export { createBooksApi } from './books'
export * as authApi from './auth'
export { isTokenExpiring, readTokenExpiryMs, TOKEN_EXPIRY_SKEW_MS } from './tokenExpiry'
export * as readingProgressApi from './readingProgress'
export * as readingTrackingApi from './readingTracking'
export * as vocabularyApi from './vocabulary'
export * as userBooksApi from './userBooks'
export type { UserBookDetailResponse } from './userBooks'
export * as insightsApi from './insights'
export * as mcpKeysApi from './mcpKeys'
export type { BookInsight } from './insights'
export * as libraryApi from './library'
export type { LibraryShelfItem, LibraryShelves } from './library'
export * as bookmarksApi from './bookmarks'
export * as dictionaryApi from './dictionary'
export * as translationApi from './translation'
export * as explainApi from './explain'
export type { ExplainRequest, ExplainResponse } from './explain'
export type { BookStatsResponse } from './readingTracking'
export * as highlightsApi from './highlights'
export type { HighlightListItem, HighlightReviewItem, PublicHighlight, HighlightListResponse } from './highlights'
export * as collectionsApi from './collections'
export type { Collection, BookType as CollectionBookType } from './collections'
