// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106222015_AddTextStackImport")]
    partial class AddTextStackImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_logs");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("ix_admin_audit_logs_action_type");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_audit_logs_admin_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_admin_audit_logs_created_at");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AdminRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_admin_refresh_tokens");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_refresh_tokens_admin_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_admin_refresh_tokens_expires_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_refresh_tokens_token");

                    b.ToTable("admin_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Indexable")
                        .HasColumnType("boolean")
                        .HasColumnName("indexable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_path");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_authors_site_id");

                    b.HasIndex("SiteId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_site_id_slug");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BookFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_book_files");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_book_files_edition_id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_book_files_sha256");

                    b.ToTable("book_files", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locator");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookmarks");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_bookmarks_chapter_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_bookmarks_edition_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_bookmarks_site_id");

                    b.HasIndex("UserId", "SiteId", "EditionId")
                        .HasDatabaseName("ix_bookmarks_user_id_site_id_edition_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.Property<string>("PlainText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plain_text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_chapters");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_chapters_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("EditionId", "ChapterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_chapters_edition_id_chapter_number");

                    b.HasIndex("EditionId", "Slug")
                        .HasDatabaseName("ix_chapters_edition_id_slug");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalOverride")
                        .HasColumnType("text")
                        .HasColumnName("canonical_override");

                    b.Property<string>("CoverPath")
                        .HasColumnType("text")
                        .HasColumnName("cover_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Indexable")
                        .HasColumnType("boolean")
                        .HasColumnName("indexable");

                    b.Property<bool>("IsPublicDomain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public_domain");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Guid?>("SourceEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_edition_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_editions_site_id");

                    b.HasIndex("SourceEditionId")
                        .HasDatabaseName("ix_editions_source_edition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_editions_status");

                    b.HasIndex("WorkId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_work_id_language");

                    b.HasIndex("SiteId", "Language", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_editions_site_id_language_slug");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EditionAuthor", b =>
                {
                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("EditionId", "AuthorId")
                        .HasName("pk_edition_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_edition_authors_author_id");

                    b.ToTable("edition_authors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Indexable")
                        .HasColumnType("boolean")
                        .HasColumnName("indexable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_genres_site_id");

                    b.HasIndex("SiteId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_site_id_slug");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BookFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_file_id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("SourceEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_edition_id");

                    b.Property<string>("SourceFormat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_format");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("target_language");

                    b.Property<string>("TextSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("text_source");

                    b.Property<int?>("UnitsCount")
                        .HasColumnType("integer")
                        .HasColumnName("units_count");

                    b.Property<string>("WarningsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_jobs");

                    b.HasIndex("BookFileId")
                        .HasDatabaseName("ix_ingestion_jobs_book_file_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ingestion_jobs_created_at");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_ingestion_jobs_edition_id");

                    b.HasIndex("SourceEditionId")
                        .HasDatabaseName("ix_ingestion_jobs_source_edition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ingestion_jobs_status");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_ingestion_jobs_work_id");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locator");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_notes_chapter_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_notes_edition_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_notes_site_id");

                    b.HasIndex("UserId", "SiteId", "EditionId")
                        .HasDatabaseName("ix_notes_user_id_site_id_edition_id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locator");

                    b.Property<double?>("Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("percent");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reading_progresses");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_reading_progresses_chapter_id");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_reading_progresses_edition_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_reading_progresses_site_id");

                    b.HasIndex("UserId", "SiteId", "EditionId")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_progresses_user_id_site_id_edition_id");

                    b.ToTable("reading_progresses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AdsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ads_enabled");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_language");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features_json");

                    b.Property<bool>("IndexingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("indexing_enabled");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("primary_domain");

                    b.Property<bool>("SitemapEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sitemap_enabled");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_code");

                    b.HasIndex("PrimaryDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_primary_domain");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SiteDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_site_domains");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_site_domains_domain");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_site_domains_site_id");

                    b.ToTable("site_domains", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TextStackImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_text_stack_imports");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_text_stack_imports_edition_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_text_stack_imports_site_id");

                    b.HasIndex("SiteId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_text_stack_imports_site_id_identifier");

                    b.ToTable("text_stack_imports", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_subject");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_libraries");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_user_libraries_edition_id");

                    b.HasIndex("UserId", "EditionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_libraries_user_id_edition_id");

                    b.ToTable("user_libraries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_works_site_id");

                    b.HasIndex("SiteId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_works_site_id_slug");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("edition_genres", b =>
                {
                    b.Property<Guid>("EditionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("editions_id");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid")
                        .HasColumnName("genres_id");

                    b.HasKey("EditionsId", "GenresId")
                        .HasName("pk_edition_genres");

                    b.HasIndex("GenresId")
                        .HasDatabaseName("ix_edition_genres_genres_id");

                    b.ToTable("edition_genres", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("Domain.Entities.AdminUser", "AdminUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_audit_logs_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Domain.Entities.AdminRefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.AdminUser", "AdminUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_refresh_tokens_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_authors_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Domain.Entities.BookFile", b =>
                {
                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany("BookFiles")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_files_editions_edition_id");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_chapters_chapter_id");

                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_editions_edition_id");

                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_sites_site_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("Chapter");

                    b.Navigation("Edition");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany("Chapters")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapters_editions_edition_id");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Domain.Entities.Edition", b =>
                {
                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_editions_sites_site_id");

                    b.HasOne("Domain.Entities.Edition", "SourceEdition")
                        .WithMany("TranslatedEditions")
                        .HasForeignKey("SourceEditionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_editions_editions_source_edition_id");

                    b.HasOne("Domain.Entities.Work", "Work")
                        .WithMany("Editions")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editions_works_work_id");

                    b.Navigation("Site");

                    b.Navigation("SourceEdition");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Domain.Entities.EditionAuthor", b =>
                {
                    b.HasOne("Domain.Entities.Author", "Author")
                        .WithMany("EditionAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_authors_authors_author_id");

                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany("EditionAuthors")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_authors_editions_edition_id");

                    b.Navigation("Author");

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_genres_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Domain.Entities.IngestionJob", b =>
                {
                    b.HasOne("Domain.Entities.BookFile", "BookFile")
                        .WithMany("IngestionJobs")
                        .HasForeignKey("BookFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_book_files_book_file_id");

                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany("IngestionJobs")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_editions_edition_id");

                    b.HasOne("Domain.Entities.Edition", "SourceEdition")
                        .WithMany()
                        .HasForeignKey("SourceEditionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ingestion_jobs_editions_source_edition_id");

                    b.HasOne("Domain.Entities.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ingestion_jobs_works_work_id");

                    b.Navigation("BookFile");

                    b.Navigation("Edition");

                    b.Navigation("SourceEdition");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Domain.Entities.Note", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_chapters_chapter_id");

                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_editions_edition_id");

                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notes_sites_site_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_users_user_id");

                    b.Navigation("Chapter");

                    b.Navigation("Edition");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_chapters_chapter_id");

                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_editions_edition_id");

                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_sites_site_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progresses_users_user_id");

                    b.Navigation("Chapter");

                    b.Navigation("Edition");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SiteDomain", b =>
                {
                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany("Domains")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_domains_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Domain.Entities.TextStackImport", b =>
                {
                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_text_stack_imports_editions_edition_id");

                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_text_stack_imports_sites_site_id");

                    b.Navigation("Edition");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Domain.Entities.UserLibrary", b =>
                {
                    b.HasOne("Domain.Entities.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_libraries_editions_edition_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_libraries_users_user_id");

                    b.Navigation("Edition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Work", b =>
                {
                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany("Works")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("edition_genres", b =>
                {
                    b.HasOne("Domain.Entities.Edition", null)
                        .WithMany()
                        .HasForeignKey("EditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_genres_editions_editions_id");

                    b.HasOne("Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_genres_genres_genres_id");
                });

            modelBuilder.Entity("Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Navigation("EditionAuthors");
                });

            modelBuilder.Entity("Domain.Entities.BookFile", b =>
                {
                    b.Navigation("IngestionJobs");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notes");

                    b.Navigation("ReadingProgresses");
                });

            modelBuilder.Entity("Domain.Entities.Edition", b =>
                {
                    b.Navigation("BookFiles");

                    b.Navigation("Chapters");

                    b.Navigation("EditionAuthors");

                    b.Navigation("IngestionJobs");

                    b.Navigation("TranslatedEditions");
                });

            modelBuilder.Entity("Domain.Entities.Site", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notes");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("UserLibraries");
                });

            modelBuilder.Entity("Domain.Entities.Work", b =>
                {
                    b.Navigation("Editions");
                });
#pragma warning restore 612, 618
        }
    }
}
