/**
 * Cross-app anchor fixtures: chapter HTML plus the passages a reader selects in it.
 *
 * A highlight is made on one client and painted on another — web, the mobile
 * WebView, or written blind by an assistant over MCP. Each producer's anchors
 * for these selections are frozen next to this file:
 *   - `web.json`    — web `createTextAnchor`, regenerated by apps/web/src/lib/crossAppAnchors.test.ts
 *   - `mobile.json` — the WebView's `getSelectionAnchor` run in jsdom, regenerated by
 *                     apps/mobile/src/lib/crossAppAnchors.test.ts
 *   - `mcp.json`    — mirrors `SynthesizeAnchor` in McpToolCatalog.cs, by hand
 * Regenerate the two generated files with `UPDATE_ANCHOR_FIXTURES=1`.
 *
 * Every consumer must resolve every producer's anchor to the same text.
 */

export interface AnchorFixtureChapter {
  /** Server chapter id — what a web anchor and a highlight row carry. */
  id: string
  slug: string
  html: string
}

export interface AnchorFixtureCase {
  name: string
  /** Chapter id the passage lives in. */
  chapter: string
  /** The selected text, exactly as it appears in the chapter's text nodes. */
  exact: string
  /** Which occurrence of `exact` in the chapter text was selected (0-based). */
  occurrence: number
}

/** A producer's anchors, keyed by case name. */
export type AnchorFixtureFile = Record<string, { prefix?: string; exact: string; suffix?: string; [k: string]: unknown }>

export const CHAPTER_A_ID = '11111111-1111-4111-8111-111111111111'
export const CHAPTER_B_ID = '22222222-2222-4222-8222-222222222222'
export const CHAPTER_UK_ID = '33333333-3333-4333-8333-333333333333'
export const CHAPTER_EDGE_ID = '44444444-4444-4444-8444-444444444444'

export const ANCHOR_CHAPTERS: AnchorFixtureChapter[] = [
  {
    id: CHAPTER_A_ID,
    slug: 'chapter-one',
    html:
      '<h1>Chapter One</h1>' +
      '<p>It was a <em>bright cold</em> day in April, and the clocks were <strong>striking</strong> thirteen.</p>' +
      '<p>The hallway smelt of boiled cabbage and old rag mats.</p>' +
      '<p>He said the word again. Nobody answered him.</p>' +
      '<p>Much later, by the window, she said the word again and the room went quiet.</p>' +
      '<p>That was the end of it.</p>',
  },
  {
    // Shares phrases with chapter A on purpose: an anchor from A must never paint here.
    id: CHAPTER_B_ID,
    slug: 'chapter-two',
    html:
      '<h1>Chapter Two</h1>' +
      '<p>In the morning he said the word again, to nobody at all.</p>' +
      '<p>The hallway smelt of boiled cabbage and old rag mats.</p>',
  },
  {
    id: CHAPTER_UK_ID,
    slug: 'rozdil-tretii',
    html:
      '<h1>Розділ третій</h1>' +
      '<p>Слово за словом, і знову <em>слово</em> — так минав день.</p>' +
      '<p dir="rtl">مرحبا بالعالم، هذه جملة قصيرة.</p>',
  },
  {
    // The same phrase opens and closes the chapter: at either edge one side of
    // the context is empty, and the other side alone has to pick the occurrence.
    id: CHAPTER_EDGE_ID,
    slug: 'edge',
    html: '<p>said the word again, and much later he said the word again</p>',
  },
]

export const ANCHOR_CASES: AnchorFixtureCase[] = [
  { name: 'chapter-start', chapter: CHAPTER_A_ID, exact: 'Chapter One', occurrence: 0 },
  { name: 'inline-tags', chapter: CHAPTER_A_ID, exact: 'bright cold day in April', occurrence: 0 },
  { name: 'across-paragraphs', chapter: CHAPTER_A_ID, exact: 'striking thirteen.The hallway', occurrence: 0 },
  { name: 'across-paragraphs-short', chapter: CHAPTER_A_ID, exact: 'thirteen.The', occurrence: 0 },
  { name: 'nbsp', chapter: CHAPTER_A_ID, exact: 'The hallway smelt', occurrence: 0 },
  { name: 'repeated-first', chapter: CHAPTER_A_ID, exact: 'said the word again', occurrence: 0 },
  { name: 'repeated-second', chapter: CHAPTER_A_ID, exact: 'said the word again', occurrence: 1 },
  { name: 'chapter-end', chapter: CHAPTER_A_ID, exact: 'end of it.', occurrence: 0 },
  { name: 'edge-repeat-start', chapter: CHAPTER_EDGE_ID, exact: 'said the word again', occurrence: 0 },
  { name: 'edge-repeat-end', chapter: CHAPTER_EDGE_ID, exact: 'said the word again', occurrence: 1 },
  { name: 'cyrillic', chapter: CHAPTER_UK_ID, exact: 'знову слово', occurrence: 0 },
  { name: 'rtl-arabic', chapter: CHAPTER_UK_ID, exact: 'بالعالم', occurrence: 0 },
]

/** Anchors only one producer makes, and the chapter text each must resolve to.
 *  An assistant quotes the plain text and has no reason to keep a U+00A0. */
export const PRODUCER_ONLY_CASES: Record<string, string> = {
  'nbsp-as-space': 'The\u00a0hallway smelt',
}

/** Start offset of the case's selection within its chapter's text. */
export function caseStart(chapterText: string, c: AnchorFixtureCase): number {
  let at = -1
  for (let i = 0; i <= c.occurrence; i++) {
    at = chapterText.indexOf(c.exact, at + 1)
    if (at === -1) throw new Error(`fixture ${c.name}: occurrence ${c.occurrence} of "${c.exact}" not in chapter`)
  }
  return at
}

export function chapterById(id: string): AnchorFixtureChapter {
  const ch = ANCHOR_CHAPTERS.find((c) => c.id === id)
  if (!ch) throw new Error(`no fixture chapter ${id}`)
  return ch
}
